import { Icon } from '@equinor/eds-core-react'
import {
    account_circle,
    accessible,
    fullscreen,
    fullscreen_exit,
    notifications,
    chevron_right,
    chevron_down,
    chevron_up,
    clear,
    pause_circle,
    stop_circle,
    play_circle,
    do_not_disturb,
    check_circle_outlined,
    error_outlined,
    time,
    warning_outlined,
    autorenew,
    pause_circle_outlined,
    remove_outlined,
    battery,
    battery_charging,
    battery_alert,
    battery_unknown,
    cloud_off,
    image,
    arrow_back,
    add,
    add_circle_outlined,
    history,
    external_link,
    pressure,
    replay,
    pin_drop,
    filter_list,
    navigation,
    settings,
    platform,
    library_add,
    play,
    edit,
    info_circle,
    blocked,
    close_circle_outlined,
    file_description,
    skip_next,
    pause,
    delete_to_trash,
    menu,
} from '@equinor/eds-icons'

Icon.add({
    account_circle,
    accessible,
    fullscreen,
    fullscreen_exit,
    notifications,
    chevron_right,
    chevron_down,
    chevron_up,
    clear,
    pause_circle,
    stop_circle,
    play_circle,
    do_not_disturb,
    check_circle_outlined,
    error_outlined,
    time,
    warning_outlined,
    autorenew,
    pause_circle_outlined,
    remove_outlined,
    battery,
    battery_charging,
    battery_alert,
    battery_unknown,
    cloud_off,
    image,
    arrow_back,
    add,
    add_circle_outlined,
    history,
    external_link,
    pressure,
    replay,
    pin_drop,
    filter_list,
    navigation,
    settings,
    platform,
    library_add,
    play,
    edit,
    info_circle,
    blocked,
    close_circle_outlined,
    file_description,
    skip_next,
    pause,
    delete_to_trash,
    menu,
})

export enum Icons {
    Account = 'account_circle',
    Accessible = 'accessible',
    Fullscreen = 'fullscreen',
    FullscreenExit = 'fullscreen_exit',
    Notifications = 'notifications',
    RightCheveron = 'chevron_right',
    DownChevron = 'chevron_down',
    UpChevron = 'chevron_up',
    Clear = 'clear',
    PauseButton = 'pause_circle',
    StopButton = 'stop_circle',
    PlayButton = 'play_circle',
    Wait = 'do_not_disturb',
    Successful = 'check_circle_outlined',
    Failed = 'error_outlined',
    Pending = 'time',
    Warning = 'warning_outlined',
    Ongoing = 'autorenew',
    Pause = 'pause_circle_outlined',
    Remove = 'remove_outlined',
    Battery = 'battery',
    BatteryCharging = 'battery_charging',
    BatteryAlert = 'battery_alert',
    BatteryUnknown = 'battery_unknown',
    CloudOff = 'cloud_off',
    Image = 'image',
    ArrowBack = 'arrow_back',
    Add = 'add',
    AddOutlined = 'add_circle_outlined',
    Historic = 'history',
    ExternalLink = 'external_link',
    Pressure = 'pressure',
    Replay = 'replay',
    PinDrop = 'pin_drop',
    Filter = 'filter_list',
    Navigation = 'navigation',
    Settings = 'settings',
    Platform = 'platform',
    LibraryAdd = 'library_add',
    PlayStandard = 'play',
    Edit = 'edit',
    Info = 'info_circle',
    Blocked = 'blocked',
    ClosedCircleOutlined = 'close_circle_outlined',
    FileDescription = 'file_description',
    Next = 'skip_next',
    PauseStandard = 'pause',
    Delete = 'delete_to_trash',
    Menu = 'menu',
}
