import { Icon } from '@equinor/eds-core-react'
import {
    accessible,
    account_circle,
    add,
    add_circle_outlined,
    arrow_back,
    autorenew,
    battery,
    battery_alert,
    battery_charging,
    battery_unknown,
    check_circle_outlined,
    chevron_down,
    clear,
    cloud_off,
    do_not_disturb,
    edit,
    error_outlined,
    external_link,
    file_description,
    filter_list,
    fullscreen,
    fullscreen_exit,
    history,
    image,
    info_circle,
    blocked,
    close_circle_outlined,
} from '@equinor/eds-icons'

Icon.add({
    accessible,
    account_circle,
    accessible,
    fullscreen,
    fullscreen_exit,
    notifications,
    chevron_down,
    clear,
    pause_circle,
    stop_circle,
    play_circle,
    do_not_disturb,
    check_circle_outlined,
    error_outlined,
    time,
    warning_outlined,
    autorenew,
    battery,
    battery_alert,
    battery_charging,
    battery_unknown,
    check_circle_outlined,
    chevron_down,
    clear,
    cloud_off,
    do_not_disturb,
    edit,
    error_outlined,
    external_link,
    file_description,
    filter_list,
    fullscreen,
    fullscreen_exit,
    history,
    image,
    info_circle,
    blocked,
    close_circle_outlined,
})

export enum Icons {
    Accessible = 'accessible',
    Account = 'account_circle',
    Add = 'add',
    AddOutlined = 'add_circle_outlined',
    ArrowBack = 'arrow_back',
    Battery = 'battery',
    BatteryAlert = 'battery_alert',
    BatteryCharging = 'battery_charging',
    BatteryUnknown = 'battery_unknown',
    Clear = 'clear',
    CloudOff = 'cloud_off',
    DropDown = 'chevron_down',
    Edit = 'edit',
    ExternalLink = 'external_link',
    Failed = 'error_outlined',
    FileDescription = 'file_description',
    Filter = 'filter_list',
    Navigation = 'navigation',
    Settings = 'settings',
    Platform = 'platform',
    LibraryAdd = 'library_add',
    LibraryPdf = 'library_pdf',
    PlayTriangle = 'play',
    Edit = 'edit',
    Info = 'info_circle',
    Blocked = 'blocked',
    ClosedCircleOutlined = 'close_circle_outlined',
}
