name: Backend

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    permissions:
      contents: read
    uses: equinor/armada/.github/workflows/test_and_lint_dotnet_package.yml@main
    with:
      build_directory: backend
