name: Deploy to Development

concurrency:
  group: development-concurrency
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - "main"

jobs:
  get-short-sha:
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - id: get-tag
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-8)
          echo "tag=$SHA_SHORT" >> "$GITHUB_OUTPUT"

  build-and-push-flotilla-components-to-github-container-registry:
    name: Build and push flotilla components to github container registry
    needs: get-short-sha
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        component: [broker, backend, frontend]
    uses: equinor/armada/.github/workflows/build_and_publish_docker_image_to_container_registry.yml@main
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}-${{ matrix.component }}
      tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      secondary_tag: dev
      path_to_dockerfile: Dockerfile
      path_to_context: ./${{ matrix.component}}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
      registry_username: ${{ github.actor }}

  deploy:
    name: Update deployment in Development
    needs: [build-and-push-flotilla-components-to-github-container-registry, get-short-sha]
    permissions:
      contents: read
    uses: ./.github/workflows/update_aurora_deployment.yml
    with:
      Environment: development
      Registry: ghcr.io
      ImageName: ${{ github.repository }}
      # Add dev. prefix for the tags used in dev environment,
      # due to the commit hash can be interpreted as an integer if only numbers
      # PS: Needs to match build-and-push-components.with.Tag
      Tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      AuthorEmail: ${{ github.event.head_commit.author.email }}
      AuthorName: ${{ github.event.head_commit.author.name }}
    secrets:
      DeployKey: ${{ secrets.ROBOTICS_INFRASTRUCTURE_DEPLOY_KEY }}
