name: Deploy to Staging

concurrency:
  group: staging-concurrency
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  packages: write

on:
  release:
    types: [published]

jobs:
  run_migrations:
    name: Update database in Staging
    permissions: 
      contents: read
      pull-requests: read
    uses: ./.github/workflows/runMigrations.yml
    with:
      PullRequestCheckout: false
      Environment: Staging
    secrets:
      ClientId: ${{secrets.CLIENTID}}
      ClientSecret: ${{secrets.CLIENTSECRET}}

  build-and-push-flotilla-components-with-latest-tag-to-github-container-registry:
    name: Build and push flotilla components with latest tag to github container registry
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        component: [broker, backend, frontend]
    uses: equinor/armada/.github/workflows/build_and_publish_docker_image_to_container_registry.yml@main
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}-${{ matrix.component }}
      tag: ${{ github.event.release.tag_name }}
      secondary_tag: latest
      path_to_dockerfile: ${{ matrix.component}}/Dockerfile
      path_to_context: ./${{ matrix.component}}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
      registry_username: ${{ github.actor }}

  build-and-push-latest-release-flotilla-component-to-aurora-prod-container-registry:
    name: Build and push latest release flotilla components to aurora prod container registry
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        component: [broker, backend, frontend]
    uses: equinor/armada/.github/workflows/build_and_publish_docker_image_to_container_registry.yml@main
    with:
      registry: auroraprodacr.azurecr.io
      image_name: robotics/flotilla-${{ matrix.component }}
      tag: ${{ github.event.release.tag_name }}
      secondary_tag: latest
      path_to_dockerfile: ${{ matrix.component}}/Dockerfile
      path_to_context: ./${{ matrix.component}}
    secrets:
      registry_password: ${{ secrets.ROBOTICS_ACRPUSH_DOCKER_SECRET }}
      registry_username: ${{ secrets.ROBOTICS_ACRPUSH_DOCKER_APPLICATION_ID }}

  deploy:
    name: Update deployment in Staging
    permissions:
      contents: read
      packages: write
    needs: build-and-push-latest-release-flotilla-component-to-aurora-prod-container-registry
    uses: ./.github/workflows/update_aurora_deployment.yml
    with:
      Environment: staging
      Registry: auroraprodacr.azurecr.io
      ImageName: robotics/flotilla
      Tag: ${{ github.event.release.tag_name }}
      AuthorName: ${{ github.event.release.author.login }}
    secrets:
      DeployKey: ${{ secrets.ROBOTICS_INFRASTRUCTURE_DEPLOY_KEY }}
