name: Update deployment in Aurora Dev

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-components:
    strategy:
      matrix:
        component: [broker, backend, frontend]
    uses: ./.github/workflows/publish_component.yml
    with:
      ComponentName: ${{ matrix.component }}
      Registry: ghcr.io
      ImageName: ${{ github.repository }}
      Tag: ${{ github.sha }}

  deploy:
    name: Update deployment in Development
    needs: [build-and-push-components]
    uses: ./.github/workflows/update_aurora_deployment.yml
    with:
      Environment: development
      Registry: ghcr.io
      ImageName: ${{ github.repository }}
      Tag: ${{ github.sha }}
      AuthorEmail: ${{ github.event.head_commit.author.email }}
      AuthorName: ${{ github.event.head_commit.author.name }}
