name: Monthly npm dependency update and create PR

on:
  schedule:
    - cron: "0 8 1 * *" # 08:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  npm-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Update npm packages (7+ day old releases only)
        run: node ${{ github.workspace }}/.github/scripts/update-npm-packages.js
        working-directory: ${{ github.workspace }}/frontend

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7
        with:
          commit-message: "GHA: Monthly npm dependency update"
          title: Monthly npm dependency update
          body: |
            - Monthly update of npm dependencies

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: monthly-npm-dependency-update
          labels: automated-pr
          delete-branch: true
