name: Notify possible migration changes

on:
  pull_request_target:
    branches: [main]
    paths: [backend/api/Database/**]

jobs:
  Notify_Possible_Migration:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files in the migrations folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: backend/api/Migrations/**

      - name: Add comment if no migrations added
        if: ${{ steps.changed-files-specific.outputs.any_changed == 'false' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            :bell: Changes in database folder detected :bell:
            Do these changes require new migrations? :thinking: In that case follow [these steps](https://github.com/equinor/flotilla/tree/main/backend#adding-a-new-migration).
            If you are uncertain, ask a database admin on the team :smile:
