name: Promote to staging

on:
  workflow_dispatch:
  # Add this when we are ready to promote to staging on release:
  # release:
  #   types: [published]

jobs:
  # TODO: Add Aurora pipeline for promotion here:
  # promote_to_aurora:

  run_migrations:
    uses: ./.github/workflows/runMigrations.yml
    with:
      PullRequestCheckout: false
      Environment: Staging
    secrets:
      ClientId: ${{secrets.CLIENTID}}
      ClientSecret: ${{secrets.CLIENTSECRET}}
