name: Promote to production

on:
  workflow_dispatch:

jobs:
  # TODO: Add Aurora pipeline for promotion here:
  # promote_to_aurora:

  run_migrations:
    uses: ./.github/workflows/runMigrations.yml
    with:
      PullRequestCheckout: false
      Environment: Production
    secrets:
      ClientId: ${{secrets.CLIENTID}}
      ClientSecret: ${{secrets.CLIENTSECRET}}
