name: Build and publish component

on:
  workflow_call:
    inputs:
      ComponentName:
        required: true
        type: string
      Registry:
        required: true
        type: string
      Tag:
        required: true
        type: string
      ImageName:
        required: true
        type: string
      SecondaryTag:
        required: false
        type: string
        default: "latest"
    secrets:
      RegistryUsername:
        required: true
      RegistryPassword:
        required: true

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Log in to the Github Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4
        with:
          registry: ${{ inputs.Registry }}
          username: ${{ secrets.RegistryUsername }}
          password: ${{ secrets.RegistryPassword }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf #v6
        with:
          images: ${{ inputs.Registry }}/${{ inputs.ImageName }}-${{ inputs.ComponentName }}

      - name: Build and push Docker image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 #v7
        with:
          context: ./${{ inputs.ComponentName }}
          push: true
          tags: |
            ${{ inputs.Registry }}/${{ inputs.ImageName }}-${{ inputs.ComponentName }}:${{ inputs.Tag }}
            ${{ inputs.Registry }}/${{ inputs.ImageName }}-${{ inputs.ComponentName }}:${{ inputs.SecondaryTag }}
          labels: ${{ steps.meta.outputs.labels }}
