name: Npm audit fix and create PR

on:
  push:
    branches:
      - main

  schedule:
    - cron: "5 6 * * 1-5" # At 06:05 on every day-of-week from Monday through Friday

permissions:
  contents: write
  pull-requests: write

jobs:
  audit-fix:
    permissions:
      contents: write
      pull-requests: write
    uses: equinor/armada/.github/workflows/npm_dependency_update_and_create_pr.yml@main
    with:
      working-directory: frontend
      node-version: "24"
      operation: audit-fix
